ppo:
  actor_critic:
    hidden_dim: 512
  hyperparameters:
    epsilon: 0.2
    steps: 5
    n_exps: 25
    print_freq: 10
    reward_threshold: 200
    gamma: 0.99
    lr: 0.0001
    episodes: 1000
    max_actions: 600

