env:
  ticker: AAPL
  interval: 1d
  period: 1y
  train_prop: 0.8
  window_size: 30
ppo:
  actor_critic:
    hidden_dim: 512
  hyperparameters:
    epsilon: 0.2
    steps: 5
    n_exps: 25
    print_freq: 10
    reward_threshold: 120
    gamma: 0.99
    lr: 0.0001
    episodes: 100
    max_actions: 600

